 'tools/python/2.7.2-ucs4' load complete.
 'tools/openmpi/1.6.3-gnu-4.1.2-ib' load complete.
 'libs/boost/1.52.0' load complete.
 'compilers/gcc/4.7.2' load complete.
 'libs/openblas/0.2.6' load complete.
 'ruby/2.0.0-p247' load complete.
Traceback (most recent call last):
  File "./pi.py", line 6, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "./pi.py", line 6, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "./pi.py", line 6, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "./pi.py", line 6, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "./pi.py", line 6, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
--------------------------------------------------------------------------
mpiexec noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
